config/routes.rb
Rails.application.routes.draw do

  resources :stats, only: :index
  resources :twits, only: [:index, :create, :update, :destroy], path_names: { create: 'api_create', update: 'api_update' }
  resources :users, only: [:index, :new, :create, :destroy]

end

app/models/twit.rb
# encoding: UTF-8
# user twits and statistics
class Twit < ActiveRecord::Base
  belongs_to :user

  validates :message, :user, presence: true

  scope :user_total_vote, lambda {
    includes(:user).group('users.name')
      .order('sum_vote DESC').sum(:vote)
  }
  scope :user_total_posts, lambda {
    joins(:user).group('users.name')
      .order('count_users_id DESC').count('users.id')
  }
  scope :user_top_posts, lambda {
    joins(:user).order('twits.vote DESC')
      .select('users.name as user_name, twits.message as message,
             twits.vote as votes')
  }

  scope :since_date, ->(date) { where('twits.created_at >= ?', date) }
  scope :twits_all, -> { joins(:user).select('users.name, twits.*') }
end

app/models/user.rb
# encoding: UTF-8

require 'securerandom'

# user model
class User < ActiveRecord::Base
  has_many :twits
  validates :name, presence: true, length: { minimum: 2 }, uniqueness: true
  before_create :set_token

  private

  def set_token
    self.token = generate_token if token.blank?
  end

  def generate_token
    SecureRandom.uuid.gsub(/\-/, '')
  end
end

app/controllers/application_controller.rb
# encoding: UTF-8

# application controller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #  protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
end

app/controllers/common_controller.rb
# encoding: UTF-8

# common controller
class CommonController < ApplicationController
  before_action :authenticate, except: [:index, :destroy]

  private

  def authenticate
    authenticate_or_request_with_http_token do |token, _options|
      @user = User.find_by(token: token)
    end
  end
end

app/controllers/stats_controller.rb
# encoding: UTF-8

# stats controller
class StatsController < ApplicationController
  def index
    d = since_date
    @top_rated = Twit.since_date(d).user_total_vote.first(5)
    @top_posters = Twit.since_date(d).user_total_posts.first(5)
    @top_posts = Twit.since_date(d).user_top_posts.first(5)
  end

  private

  def since_date
    if params[:date] == 'today'
      d = Date.today.at_beginning_of_day
    elsif params[:date] == 'this_week'
      d = Date.today.at_beginning_of_week
    end
    d || 10.years.ago
  end
end

app/controllers/twits_controller.rb
# encoding: UTF-8

# twits controller
class TwitsController < CommonController
  def index
    @twits = Twit.twits_all
  end

  def create
    @twit = @user.twits.create(twit_params)
    @twit.save
    redirect_to twits_path
  end

  def update
    @twit = Twit.find(params[:id])
    @twit.increment!(:vote)
    redirect_to twits_path
  end

  def destroy
    @twit = Twit.find(params[:id])
    @twit.destroy
    redirect_to twits_path
  end

  private

  def twit_params
    params.require(:twit).permit(:message, :string)
  end
end

app/controllers/users_controller.rb
# encoding: utf-8

# users controller
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :token)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twits</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stats/index.html.erb
<h1>Statistics</h1>

<div>
    <%= form_tag '', :method => :get do %>
        <%= radio_button_tag(:date, "all", params[:date] == 'all' || params[:date] == nil) %>
        <%= label_tag(:lbl, "all") %>
        <%= radio_button_tag(:date, "today", params[:date] == 'today') %>
        <%= label_tag(:lbl, "today") %>
        <%= radio_button_tag(:date, "this_week", params[:date] == 'this_week') %>
        <%= label_tag(:lbl, "this week") %>
        <p><%= submit_tag 'Apply' %></p>
    <% end %>
</div>

<div>
    <table>
        <tr bgcolor="#81BEF7">
            <th>User</th>
            <th>Votes</th>
        </tr>
        <% @top_rated.each do |user| %>
            <tr>
            <td><%= user[0] %></td>
            <td><%= user[1] %></td>
        </tr>
    <% end %>
    </table>
</div>

<div>
    <table>
        <tr bgcolor="#81BEF7">
            <th>User</th>
            <th>Posts</th>
        </tr>
        <% @top_posters.each do |user| %>
            <tr>
            <td><%= user[0] %></td>
            <td><%= user[1] %></td>
        </tr>
    <% end %>
    </table>
</div>

<div>
    <table>
        <tr bgcolor="#81BEF7">
            <th>User</th>
            <th>Message</th>
            <th>Votes</th>
        </tr>
        <% @top_posts.each do |post| %>
        <tr>
            <td><%= post.user_name %></td>
            <td><%= post.message %></td>
            <td><%= post.votes%></td>
        </tr>
    <% end %>
    </table>
</div>

app/views/twits/_twit.html.erb
<tr>
    <td><%= twit.name %></td>
    <td><%= twit.message %></td>
    <td><%= twit.vote %></td>
    <td><%= link_to 'delete', twit_path(twit),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/twits/index.html.erb
<h1>Twits</h1>
<div>
    <table>
        <tr bgcolor="#81BEF7">
            <th>User</th>
            <th>Message</th>
            <th>Votes</th>
        </tr>
        <%= render @twits %>
    </table>
</div>

app/views/users/_user.html.erb
<tr>
  <td><%= user.name %></td>
  <td><%= user.token %></td>
  <td><%= link_to 'delete', user_path(user),
          method: :delete,
          data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/users/index.html.erb
<h1>Users</h1>
 
<table>
  <tr bgcolor="#81BEF7">
    <th>Name</th>
    <th>Token</th>
  </tr>
 
  <%= render @users %>
</table>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
 <% if @user.errors.any? %>
    <div>
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
  </div>

<% end %>